import { chromium } from 'playwright-core'
const browser = await chromium.launch({ executablePath: '/opt/pw-browsers/chromium-1194/chrome-linux/chrome' })
const page = await browser.newPage({ viewport: { width: 1440, height: 900 } })
page.on('pageerror', (e) => console.log('ERREUR', e.message))
page.on('console', (m) => { if (m.type()==='error') console.log('CONSOLE', m.text().slice(0,200)) })
await page.goto('http://localhost:5199')
await page.waitForTimeout(4000)
console.log(await page.title())
console.log((await page.locator('body').innerText()).slice(0, 1500))
await browser.close()
